version: "0"
name: simple-form
services:
  develop:
    image: vite-react-ts-project
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-form
    volumes:
      - .:/app
      - ./src:/app
      - ./public:/app
      - ./node_modules:/app
    ports:
      - 5240:5173
